
<?php

	if ( ! isset( $_SESSION[ "logged" ] ) )   die('ao`?');

	include( dirname( __FILE__ ) . '/../_header.phtml' );

?>

<div class="container container-page">

	<div class="row">
		<div class="col-xs-offset-1 col-xs-10 col-md-offset-3 col-md-6 well">

		<?
			if( !empty( $infoMsg) ){
			?>
			<div class="alert alert-info" role="alert"><?= $infoMsg ?></div>
			<?
			}
		?>

		<?
			if( !empty( $errorMsg) ){
			?>
			<div class="alert alert-danger" role="alert"><?= $errorMsg ?></div>
			<?
			}
		?>

			<div class="row">
				<div class="col-sm-12 form-canvas">

					<form name="form-login" action="" method="post" enctype='multipart/form-data' class="" role="form">

						<input type="hidden" name="action" value="submit_data" >

						<div class="form-group">
							<label for="file_fattura" class="control-label">File esportato per FATTURA:</label>
							<input class="form-control" required type="file" name="file_fattura" id="file_fattura"  />
						</div>
						<div class="form-group">
							<label for="file_ddt" class="control-label">File esportato per DDT:</label>
							<input class="form-control" required type="file" name="file_ddt" id="file_ddt"  />
						</div>
						<button id="formSubmit" type="submit" class="btn btn-primary ">Magia</button>

					</form>

				</div>
			</div>
		</div>
	</div>
</div>

<?php

	include( dirname( __FILE__ ) . '/../_footer.phtml' );

?>
