<?php

	include( dirname( __FILE__ ) . '/../_header.phtml' );

?>


<div class="container container-page">

	<div class="row">
		<div class="col-xs-offset-1 col-xs-10 col-md-offset-4 col-md-4 logo">
			<h1 class="text-center"><span class="fa fa-rocket"></span> PinsaLab</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-offset-1 col-xs-10 col-md-offset-3 col-md-6 well">

		<?
			if( !empty( $infoMsg) ){
			?>
			<div class="alert alert-info" role="alert"><?= $infoMsg ?></div>
			<?
			}
		?>

		<?
			if( !empty( $errorMsg) ){
			?>
			<div class="alert alert-danger" role="alert"><?= $errorMsg ?></div>
			<?
			}
		?>

			<div class="row">
				<div class="col-sm-12 form-canvas">

					<form name="form-login" action="" method="post"  class="" role="form">

						<input type="hidden" name="action" value="login" >

						<div class="form-group">
							<label for="username">Username:</label>
							<input type="text" required class="form-control" value="" id="username" name="username" />
						</div>
						<div class="form-group">
							<label for="password">Password:</label>
							<input type="password" required class="form-control" value="" id="password" name="password" />
						</div>
						<button id="formSubmit" type="submit" class="btn btn-primary ">Entra</button>
					</form>

				</div>
			</div>
		</div>
	</div>
</div>


<?php

	include( dirname( __FILE__ ) . '/../_footer.phtml' );

?>
