<?php

if ( !defined('MALEDETTOCONAD'))        die('no direct access allowed');

?>
<!DOCTYPE html>
<html lang="IT">
<head>
	<meta charset="UTF-8">

	<title>Conad Invoice Exporter</title>
	<meta name="viewport"                     content="width=device-width, initial-scale=1.0">
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="description"                  content="Administration panel for Fabio">
	<meta name="author"                       content="Io">
	<!-- Le styles -->


	<!-- INCLUDE JQUERY -->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

	<!-- INCLUDE BOOTSTRAP -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<!-- FONT AWESOME -->
	<script src="https://use.fontawesome.com/7fdd05333a.js"></script>

	<!-- MY CSS -->
	<link rel="stylesheet" type="text/css" href="inc/style.css" />

	<!-- MY JS -->
	<script type="text/javascript" src="inc/scripts.js"></script>

</head>

<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href=""><span class="fa fa-rocket"></span> Conad Invoice Exporter</a>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="navbar-collapse">
		<ul class="nav navbar-nav">


		</ul>
	</div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
